// Copies the Lucide icons the app uses (lucide-static, ISC licence) into
// resources/icons/lucide.php, so <x-icon> renders inline SVG with no runtime
// dependency. Add a name to ICONS and run: node scripts/icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = `
activity arrow-down-right arrow-left arrow-right arrow-up-right badge-check bell building-2 calendar
chart-column chart-pie check chevron-down chevron-left chevron-right chevron-up circle-alert circle-check
circle-user clipboard-list clock cloud-check cloud-off cloud-upload command copy database download ellipsis
external-link eye eye-off file-text flag flame funnel gauge grip handshake heart-pulse house inbox info
key-round landmark layers layout-dashboard list-todo loader-circle lock log-out mail map map-pin map-pinned
medal megaphone menu message-square monitor moon newspaper palette panel-left pencil phone plus printer
radio refresh-cw rotate-ccw scroll-text search server settings shield shield-check sliders-horizontal
smartphone sparkle sparkles square-check-big sun target trash-2 trending-down trending-up triangle-alert
trophy upload user send user-plus user-round-check users vote wifi-off x zap minus circle-dot star
`.trim().split(/\s+/).sort();

const entries = ICONS.map((name) => {
  const svg = readFileSync(new URL(`../node_modules/lucide-static/icons/${name}.svg`, import.meta.url), 'utf8');
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s*\n\s*/g, '')
    .replace(/\s+\/>/g, '/>');
  return `    '${name}' => '${inner.replace(/'/g, "\\'")}',`;
});

writeFileSync(
  new URL('../resources/icons/lucide.php', import.meta.url),
  `<?php\n\n// Generated by scripts/icons.mjs from lucide-static (ISC licence). Do not edit.\n\nreturn [\n${entries.join('\n')}\n];\n`,
);

console.log(`Wrote ${entries.length} icons.`);
