<?php

namespace App\Support;

/**
 * Lucide icons as inline SVG (resources/icons/lucide.php, generated by
 * scripts/icons.mjs). Unknown names render a small circle, never an error.
 */
class Icons
{
    /** @var array<string, string>|null */
    private static ?array $icons = null;

    public static function paths(string $name): string
    {
        self::$icons ??= require resource_path('icons/lucide.php');

        return self::$icons[$name] ?? '<circle cx="12" cy="12" r="4"/>';
    }

    public static function has(string $name): bool
    {
        self::$icons ??= require resource_path('icons/lucide.php');

        return isset(self::$icons[$name]);
    }

    /**
     * @return list<string>
     */
    public static function names(): array
    {
        self::$icons ??= require resource_path('icons/lucide.php');

        return array_keys(self::$icons);
    }
}
